eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8081
spring:
  application:
    name: creditShower

application:
  config:
    database-server-url: http://localhost:8082/api/v1/DatabaseServer

management:
  tracing:
    sampling:
      probability: 1.0
