eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8082
spring:
  application:
    name: database-server


management:
  tracing:
    sampling:
      probability: 1.0
